import type {
  Cluster,
  DomainEvent,
  Integration,
  Model,
  NetworkPath,
  Node,
  PlacementDecision,
  Site,
  TopologyLink,
  TopologyNode,
  Workload,
  WorldSnapshot,
} from "./types";

const SEED = 42;

function evt(
  type: string,
  message: string,
  severity: DomainEvent["severity"] = "info",
  meta?: DomainEvent["meta"],
): DomainEvent {
  return {
    id: `evt-${Math.random().toString(36).slice(2, 9)}`,
    type,
    message,
    severity,
    at: new Date().toISOString(),
    meta,
  };
}

export function createSeedWorld(): WorldSnapshot {
  const sites: Site[] = [
    {
      id: "site-mad",
      name: "Madrid Edge",
      region: "EU",
      country: "ES",
      status: "HEALTHY",
      clusterIds: ["cls-mad-k3s", "cls-mad-ke"],
    },
    {
      id: "site-bcn",
      name: "Barcelona MEC",
      region: "EU",
      country: "ES",
      status: "HEALTHY",
      clusterIds: ["cls-bcn-k8s"],
    },
    {
      id: "site-lis",
      name: "Lisbon Edge",
      region: "EU",
      country: "PT",
      status: "WARNING",
      clusterIds: ["cls-lis-k3s"],
    },
  ];

  const clusters: Cluster[] = [
    {
      id: "cls-mad-k3s",
      name: "madrid-02",
      provider: "k3s",
      version: "v1.30.2+k3s1",
      region: "EU",
      country: "ES",
      location: "Madrid",
      status: "HEALTHY",
      mode: "SIMULATION",
      nodeIds: ["node-mad-01", "node-mad-04", "node-mad-07"],
      labels: { tier: "edge", zone: "mad-a" },
      capabilities: ["gpu", "inference", "low-latency"],
      latencyMs: 6,
    },
    {
      id: "cls-mad-ke",
      name: "madrid-kubeedge",
      provider: "kubeedge",
      version: "v1.18.0",
      region: "EU",
      country: "ES",
      location: "Madrid",
      status: "HEALTHY",
      mode: "SIMULATION",
      nodeIds: ["node-mad-edge-02"],
      labels: { tier: "far-edge" },
      capabilities: ["offline-tolerant", "cpu"],
      latencyMs: 9,
    },
    {
      id: "cls-bcn-k8s",
      name: "barcelona-01",
      provider: "kubernetes",
      version: "v1.31.0",
      region: "EU",
      country: "ES",
      location: "Barcelona",
      status: "HEALTHY",
      mode: "SIMULATION",
      nodeIds: ["node-bcn-01", "node-bcn-03"],
      labels: { tier: "regional" },
      capabilities: ["gpu", "batch", "storage"],
      latencyMs: 14,
    },
    {
      id: "cls-lis-k3s",
      name: "lisbon-01",
      provider: "k3s",
      version: "v1.29.8+k3s1",
      region: "EU",
      country: "PT",
      location: "Lisbon",
      status: "DEGRADED",
      mode: "SIMULATION",
      nodeIds: ["node-lis-01", "node-lis-02"],
      labels: { tier: "edge" },
      capabilities: ["gpu", "inference"],
      latencyMs: 18,
    },
  ];

  const nodes: Node[] = [
    mkNode("node-mad-01", "EDGE-MAD-01", "cls-mad-k3s", "site-mad", {
      cpuUsedPct: 38,
      ramUsedPct: 52,
      gpuUsedPct: 41,
      vramUsedPct: 33,
      rttMs: 5.2,
      powerW: 162,
      temperatureC: 58,
    }),
    mkNode("node-mad-04", "EDGE-MAD-04", "cls-mad-k3s", "site-mad", {
      cpuUsedPct: 42,
      ramUsedPct: 61,
      gpuUsedPct: 48,
      vramUsedPct: 37,
      rttMs: 6.0,
      powerW: 184,
      temperatureC: 61,
      accelerator: "NVIDIA L4",
    }),
    mkNode("node-mad-07", "EDGE-MAD-07", "cls-mad-k3s", "site-mad", {
      cpuUsedPct: 28,
      ramUsedPct: 44,
      gpuUsedPct: 22,
      vramUsedPct: 18,
      rttMs: 6.4,
      powerW: 148,
      temperatureC: 54,
      accelerator: "NVIDIA L4",
    }),
    mkNode("node-mad-edge-02", "EDGE-MAD-FE-02", "cls-mad-ke", "site-mad", {
      cpuUsedPct: 55,
      ramUsedPct: 63,
      gpuCount: 0,
      gpuUsedPct: 0,
      vramGi: 0,
      vramUsedPct: 0,
      rttMs: 8.5,
      powerW: 72,
      temperatureC: 49,
      accelerator: undefined,
    }),
    mkNode("node-bcn-01", "EDGE-BCN-01", "cls-bcn-k8s", "site-bcn", {
      cpuUsedPct: 47,
      ramUsedPct: 58,
      gpuUsedPct: 55,
      vramUsedPct: 49,
      rttMs: 12.1,
      powerW: 210,
      temperatureC: 64,
      accelerator: "NVIDIA A10",
    }),
    mkNode("node-bcn-03", "EDGE-BCN-03", "cls-bcn-k8s", "site-bcn", {
      cpuUsedPct: 33,
      ramUsedPct: 40,
      gpuUsedPct: 15,
      vramUsedPct: 12,
      rttMs: 13.4,
      powerW: 176,
      temperatureC: 57,
      accelerator: "NVIDIA A10",
    }),
    mkNode("node-lis-01", "EDGE-LIS-01", "cls-lis-k3s", "site-lis", {
      cpuUsedPct: 71,
      ramUsedPct: 78,
      gpuUsedPct: 88,
      vramUsedPct: 81,
      rttMs: 17.8,
      powerW: 240,
      temperatureC: 72,
      status: "DEGRADED",
      accelerator: "NVIDIA T4",
    }),
    mkNode("node-lis-02", "EDGE-LIS-02", "cls-lis-k3s", "site-lis", {
      cpuUsedPct: 64,
      ramUsedPct: 70,
      gpuUsedPct: 76,
      vramUsedPct: 69,
      rttMs: 19.2,
      powerW: 228,
      temperatureC: 70,
      status: "WARNING",
      accelerator: "NVIDIA T4",
    }),
  ];

  const models: Model[] = [
    {
      id: "mdl-traffic-14",
      name: "traffic-detector",
      version: "1.4.2",
      runtime: "onnxruntime",
      architecture: "YOLOv8n",
      sizeMb: 12.4,
      sha256: "a3f9c2e1b8d04765e90f1a2b3c4d5e6f7890abcd",
      gpuCompatible: true,
      status: "deployed",
      mode: "SIMULATION",
    },
    {
      id: "mdl-traffic-13",
      name: "traffic-detector",
      version: "1.3.0",
      runtime: "onnxruntime",
      architecture: "YOLOv8n",
      sizeMb: 11.8,
      sha256: "bb12cd34ef56aa78bb90cc112233445566778899",
      gpuCompatible: true,
      status: "validated",
      mode: "SIMULATION",
    },
    {
      id: "mdl-anomalydet",
      name: "cell-anomaly",
      version: "0.9.1",
      runtime: "onnxruntime",
      architecture: "Transformer-S",
      sizeMb: 48.2,
      sha256: "cc99ee11ff22aa33bb44cc55dd66ee77ff889900",
      gpuCompatible: true,
      status: "validated",
      mode: "SIMULATION",
    },
  ];

  const workloads: Workload[] = [
    {
      id: "wl-traffic-vision",
      name: "traffic-vision",
      type: "ai-inference",
      status: "Running",
      image: "registry.example.com/traffic-vision:1.4.2",
      modelId: "mdl-traffic-14",
      clusterId: "cls-mad-k3s",
      nodeId: "node-mad-04",
      cpu: 4,
      memoryGi: 8,
      gpu: 1,
      gpuMemoryGi: 8,
      maxLatencyMs: 20,
      minBandwidthMbps: 30,
      region: "EU",
      allowedRegions: ["EU"],
      availability: 99.9,
      requestsPerSec: 1842,
      inferenceLatencyMs: 8.1,
      networkLatencyMs: 4.1,
      e2eLatencyMs: 12.2,
      errorRatePct: 0.12,
      version: "1.4.2",
    },
    {
      id: "wl-cell-monitor",
      name: "cell-monitor",
      type: "edge-application",
      status: "Running",
      image: "registry.example.com/cell-monitor:2.1.0",
      clusterId: "cls-mad-ke",
      nodeId: "node-mad-edge-02",
      cpu: 2,
      memoryGi: 4,
      gpu: 0,
      gpuMemoryGi: 0,
      maxLatencyMs: 50,
      minBandwidthMbps: 10,
      region: "EU",
      allowedRegions: ["EU"],
      availability: 99.5,
      requestsPerSec: 420,
      inferenceLatencyMs: 0,
      networkLatencyMs: 8.5,
      e2eLatencyMs: 8.5,
      errorRatePct: 0.05,
      version: "2.1.0",
    },
    {
      id: "wl-batch-retrain",
      name: "nightly-retrain",
      type: "batch",
      status: "Stopped",
      image: "registry.example.com/retrain:0.3",
      modelId: "mdl-anomalydet",
      clusterId: "cls-bcn-k8s",
      nodeId: "node-bcn-01",
      cpu: 8,
      memoryGi: 32,
      gpu: 1,
      gpuMemoryGi: 16,
      maxLatencyMs: 500,
      minBandwidthMbps: 100,
      region: "EU",
      allowedRegions: ["EU"],
      availability: 99.0,
      requestsPerSec: 0,
      inferenceLatencyMs: 0,
      networkLatencyMs: 0,
      e2eLatencyMs: 0,
      errorRatePct: 0,
      version: "0.3.0",
    },
  ];

  const topologyNodes: TopologyNode[] = [
    { id: "topo-ue", kind: "ue", label: "UE-1042", x: 40, y: 220, status: "HEALTHY" },
    { id: "topo-gnb", kind: "gnb", label: "gNB-03", x: 160, y: 220, status: "HEALTHY" },
    { id: "topo-ovs1", kind: "ovs", label: "OVS-12", x: 300, y: 160, status: "HEALTHY" },
    { id: "topo-ovs2", kind: "ovs", label: "OVS-17", x: 440, y: 120, status: "HEALTHY" },
    { id: "topo-ovs3", kind: "ovs", label: "OVS-21", x: 440, y: 280, status: "HEALTHY" },
    {
      id: "topo-edge-mad04",
      kind: "edge",
      label: "EDGE-MAD-04",
      x: 600,
      y: 120,
      refId: "node-mad-04",
      status: "HEALTHY",
    },
    {
      id: "topo-edge-mad07",
      kind: "edge",
      label: "EDGE-MAD-07",
      x: 600,
      y: 280,
      refId: "node-mad-07",
      status: "HEALTHY",
    },
    {
      id: "topo-gpu-a",
      kind: "gpu",
      label: "GPU L4",
      x: 740,
      y: 120,
      status: "HEALTHY",
    },
    {
      id: "topo-gpu-b",
      kind: "gpu",
      label: "GPU L4",
      x: 740,
      y: 280,
      status: "HEALTHY",
    },
    {
      id: "topo-wl",
      kind: "workload",
      label: "traffic-vision",
      x: 880,
      y: 120,
      refId: "wl-traffic-vision",
      status: "HEALTHY",
    },
  ];

  const topologyLinks: TopologyLink[] = [
    link("l1", "topo-ue", "topo-gnb", 1.2, 1, 22),
    link("l2", "topo-gnb", "topo-ovs1", 0.8, 10, 31),
    link("l3", "topo-ovs1", "topo-ovs2", 2.1, 10, 42),
    link("l4", "topo-ovs1", "topo-ovs3", 1.6, 10, 18),
    link("l5", "topo-ovs2", "topo-edge-mad04", 1.4, 10, 38),
    link("l6", "topo-ovs3", "topo-edge-mad07", 1.5, 10, 12),
    link("l7", "topo-edge-mad04", "topo-gpu-a", 0.3, 25, 48),
    link("l8", "topo-edge-mad07", "topo-gpu-b", 0.3, 25, 22),
    link("l9", "topo-gpu-a", "topo-wl", 0.1, 25, 48),
  ];

  const paths: NetworkPath[] = [
    {
      id: "path-ue-tv",
      ueId: "UE-1042",
      workloadId: "wl-traffic-vision",
      hops: [
        "UE-1042",
        "gNB-03",
        "OVS-12",
        "OVS-17",
        "EDGE-MAD-04",
        "traffic-vision v1.4",
      ],
      networkLatencyMs: 4.1,
      inferenceLatencyMs: 8.1,
      e2eLatencyMs: 12.2,
      packetLossPct: 0.02,
      bandwidthMbps: 83,
    },
  ];

  const decisions: PlacementDecision[] = [
    {
      id: "dec-001",
      workloadId: "wl-traffic-vision",
      workloadName: "traffic-vision",
      selectedNodeId: "node-mad-04",
      selectedNodeName: "EDGE-MAD-04",
      score: 99,
      factors: [
        { label: "GPU compatible", points: 25, detail: "NVIDIA L4 matches requirement" },
        { label: "GPU availability", points: 18, detail: "48% util, 1 GPU free slot" },
        { label: "Latency 6ms", points: 20, detail: "Under 20ms SLA" },
        { label: "Bandwidth 1Gbps+", points: 10, detail: "1.2 Gbps available" },
        { label: "EU residency", points: 10, detail: "Madrid / ES" },
        { label: "Healthy node", points: 8, detail: "Agent online, no taints" },
        { label: "Low congestion", points: 5, detail: "Path util < 50%" },
        { label: "Energy efficiency", points: 3, detail: "184W within envelope" },
      ],
      rejected: [
        { nodeId: "node-lis-01", nodeName: "EDGE-LIS-01", reason: "GPU util 88%, latency 17.8ms risk" },
        { nodeId: "node-mad-edge-02", nodeName: "EDGE-MAD-FE-02", reason: "No GPU" },
        { nodeId: "node-bcn-01", nodeName: "EDGE-BCN-01", reason: "Latency 12.1ms higher than Madrid edge" },
      ],
      createdAt: new Date(Date.now() - 3600_000).toISOString(),
      reasonSummary: "Best GPU + lowest EU edge latency with residency compliance.",
    },
  ];

  const integrations: Integration[] = [
    {
      id: "int-k8s",
      name: "Kubernetes",
      status: "SIMULATION",
      version: "1.31",
      health: "HEALTHY",
      capabilities: ["deploy", "scale", "drain"],
    },
    {
      id: "int-k3s",
      name: "K3s",
      status: "SIMULATION",
      version: "1.30",
      health: "HEALTHY",
      capabilities: ["deploy", "edge"],
    },
    {
      id: "int-ke",
      name: "KubeEdge",
      status: "SIMULATION",
      version: "1.18",
      health: "HEALTHY",
      capabilities: ["far-edge", "offline"],
    },
    {
      id: "int-ovs",
      name: "Open vSwitch",
      status: "SIMULATION",
      version: "3.3",
      health: "HEALTHY",
      capabilities: ["flows", "qos"],
    },
    {
      id: "int-otel",
      name: "OpenTelemetry",
      status: "SIMULATION",
      version: "1.0",
      health: "HEALTHY",
      capabilities: ["traces", "metrics"],
    },
    {
      id: "int-prom",
      name: "Prometheus",
      status: "SIMULATION",
      version: "2.54",
      health: "HEALTHY",
      capabilities: ["metrics", "alerts"],
    },
    {
      id: "int-mec",
      name: "ETSI MEC",
      status: "SIMULATION",
      version: "—",
      health: "WARNING",
      capabilities: ["app-enablement"],
    },
    {
      id: "int-oran",
      name: "O-RAN",
      status: "SIMULATION",
      version: "—",
      health: "WARNING",
      capabilities: ["near-rt-ric"],
    },
    {
      id: "int-nvidia",
      name: "NVIDIA",
      status: "SIMULATION",
      version: "—",
      health: "WARNING",
      capabilities: ["gpu", "nim"],
    },
  ];

  const events: DomainEvent[] = [
    evt("ClusterRegistered", "Cluster madrid-02 registered (k3s)"),
    evt("NodeRegistered", "EDGE-MAD-04 joined madrid-02"),
    evt("WorkloadScheduled", "traffic-vision scheduled on EDGE-MAD-04"),
    evt("WorkloadDeployed", "traffic-vision Running on EDGE-MAD-04"),
    evt("RouteChanged", "Path UE-1042 → EDGE-MAD-04 via OVS-17 established"),
  ];

  return {
    tenant: { id: "tenant-demo", name: "Demo Operator" },
    role: "Platform Admin",
    mode: "SIMULATION",
    sites,
    clusters,
    nodes,
    workloads,
    models,
    topology: { nodes: topologyNodes, links: topologyLinks },
    paths,
    decisions,
    events,
    integrations,
    metrics: {
      inferenceRps: 2262,
      avgLatencyMs: 11.4,
      p95LatencyMs: 18.6,
      gpuUtilPct: 49,
      networkHealthPct: 97,
      energyKw: 1.42,
      activeMigrations: 0,
      incidents: 1,
    },
    simulation: {
      running: true,
      scenario: "Normal Edge Network",
      tick: 0,
      seed: SEED,
    },
  };
}

function mkNode(
  id: string,
  name: string,
  clusterId: string,
  siteId: string,
  partial: Partial<Node> & {
    cpuUsedPct: number;
    ramUsedPct: number;
    gpuUsedPct: number;
    vramUsedPct: number;
    rttMs: number;
    powerW: number;
    temperatureC: number;
  },
): Node {
  return {
    id,
    name,
    clusterId,
    siteId,
    region: "EU",
    status: partial.status ?? "HEALTHY",
    mode: "SIMULATION",
    cpuCores: partial.cpuCores ?? 16,
    cpuUsedPct: partial.cpuUsedPct,
    ramGi: partial.ramGi ?? 64,
    ramUsedPct: partial.ramUsedPct,
    gpuCount: partial.gpuCount ?? 1,
    gpuUsedPct: partial.gpuUsedPct,
    vramGi: partial.vramGi ?? 24,
    vramUsedPct: partial.vramUsedPct,
    storageUsedPct: partial.storageUsedPct ?? 52,
    accelerator: partial.accelerator ?? "NVIDIA L4",
    rttMs: partial.rttMs,
    bandwidthGbps: partial.bandwidthGbps ?? 1.2,
    packetLossPct: partial.packetLossPct ?? 0.01,
    powerW: partial.powerW,
    temperatureC: partial.temperatureC,
    cordoned: false,
    drained: false,
    labels: { zone: "edge" },
    taints: [],
    agentStatus: "online",
  };
}

function link(
  id: string,
  from: string,
  to: string,
  latencyMs: number,
  bandwidthGbps: number,
  utilizationPct: number,
): TopologyLink {
  return {
    id,
    from,
    to,
    latencyMs,
    bandwidthGbps,
    utilizationPct,
    packetLossPct: 0.01,
    congested: false,
  };
}
